### PR TITLE
Add Cyclone scheme to the R7RS benchmark script

### PR DESCRIPTION
**Pull request by justinethier**
Thanks for maintaining such an excellent set of benchmarks. This is a request to add the [Cyclone](http://justinethier.github.io/cyclone/) compiler to the benchmark suite.

### CODE REVIEW

**Comment by WillClinger** [comment]
I'd like to install cyclone before accepting this pull request, because I'll need cyclone for testing it anyway, but the ```./install.sh``` script mentioned by ```https://github.com/justinethier/cyclone-bootstrap``` doesn't exist in the v0.0.7.tar.gz I downloaded.  Rather than guess, I'll await further instructions.

**Comment by WillClinger** [comment]
I'd like to install cyclone before accepting this pull request, because I'll need cyclone for testing it anyway, but the ```./install.sh``` script mentioned by ```https://github.com/justinethier/cyclone-bootstrap``` doesn't exist in the v0.0.7.tar.gz I downloaded.  Rather than guess, I'll await further instructions.

**Comment by justinethier** [comment]
Sorry about that. The install script is included in the cyclone-bootstrap download, which you need to use when installing the first time:

https://github.com/justinethier/cyclone-bootstrap/releases

I just double-checked and that download includes the `install.sh` script, as well as the rest of the files from that repo. 

You also need to install concurrency kit to get everything to build. There are instructions here:

https://github.com/justinethier/cyclone-bootstrap

Please let me know if you run into trouble.

**Comment by WillClinger** [comment]
Thanks.  I have installed Cyclone, run the R7RS benchmarks, and updated the relevant web pages.

Cyclone was unable to run some of the benchmarks, which is also true for most other implementations of the R7RS.  In addition, I noticed these things, of which you're probably already aware:

1. An inexact integer such as 3.0 prints the same as an exact integer 3.
1. Although ```(features)``` lists ```exact-closed```, that isn't true.
1. When computing with exact integers, overflow is not detected, yielding incorrect results.

**Comment by justinethier** [comment]
You're welcome, Will. Thanks for taking the time to install Cyclone and re-run your benchmarks.

Thank you for reporting these issues, and please feel free to report any additional problems you run into. Part of the problem with Cyclone being a relatively new project is working through issues like these. Hopefully the project will be able to improve over time, including passing more benchmarks and fixing these issues.

Anyway, thanks again and Happy 4th! :)

**Pull request merged**
